language: elixir
os: linux

elixir: "1.9.4"
otp_release: "22.2"

stages:
  - check formatted
  - test
  - dialyzer

jobs:
  include:
    - stage: test
    - stage: check formatted
      script: mix format --check-formatted
    - stage: dialyzer
cache:
  directories:
    - plts
